### ISSUE TITLE
fix bugs

### ISSUE THREAD

**Issue by Farouk-ayo** [Khay0000/Brew#1]

**Comment by Khay0000** [comment]
you no write anything o?

**Comment by Farouk-ayo** [comment]
oh you dey online sef..........i wanted to try this approach before but its a lnng process (write access and the likes.......
i'll fork your repo and make a PR now sha

**Comment by Farouk-ayo** [comment]
just add me as a collaborator to that repo
by checking under settings ......you'll see the option there
